<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HB25A9N" failures="2" tests="16" name="Power Function Unit Test" time="0.012" errors="0" timestamp="2024-03-12T13:31:18 MSK">
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitNegativePowDoubleTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Expected IllegalArgumentException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected IllegalArgumentException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTest.PowTest.unitNegativePowDoubleTest(PowTest.java:33)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitNegativePowDoubleTest -->
  <testcase classname="org.rntgroup.CalcUnitTest.SqrtTest" name="unitNegativePowDoubleTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Expected ArithmeticException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected ArithmeticException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTest.SqrtTest.unitNegativePowDoubleTest(SqrtTest.java:29)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitNegativePowDoubleTest -->
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitPowTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.SqrtTest" name="unitSqrtTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.SqrtTest" name="unitSqrtTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitPowTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.SqrtTest" name="unitSqrtTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitPowTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitPowTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.SqrtTest" name="unitSqrtTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitPowTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.SqrtTest" name="unitSqrtTest" time="0.001"/>
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitPowTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitPowTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitPowTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTest.PowTest" name="unitPowTest" time="0.0"/>
</testsuite> <!-- Power Function Unit Test -->
