<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HB25A9N" failures="1" tests="5" name="org.rntgroup.CalcUnitTests.DivLongTest" time="0.004" errors="0" timestamp="2024-02-29T13:20:20 MSK" skipped="0">
  <testcase classname="org.rntgroup.CalcUnitTests.DivLongTest" name="unitDivLongTest" time="0.000"/>
  <testcase classname="org.rntgroup.CalcUnitTests.DivLongTest" name="unitDivLongTest" time="0.002"/>
  <testcase classname="org.rntgroup.CalcUnitTests.DivLongTest" name="unitDivLongTest" time="0.000"/>
  <testcase classname="org.rntgroup.CalcUnitTests.DivLongTest" name="unitDivLongTest" time="0.000"/>
  <testcase classname="org.rntgroup.CalcUnitTests.DivLongTest" name="unitDivByZeroLongTest" time="0.002">
    <failure message="Expected ArithmeticException to be thrown, but NumberFormatException was thrown" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected ArithmeticException to be thrown, but NumberFormatException was thrown
at org.testng.Assert.expectThrows(Assert.java:2454)
at org.testng.Assert.expectThrows(Assert.java:2425)
at org.testng.Assert.assertThrows(Assert.java:2391)
at org.rntgroup.CalcUnitTests.DivLongTest.unitDivByZeroLongTest(DivLongTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NumberFormatException: Attempt to divide by zero
at com.epam.tat.module4.Calculator.div(Calculator.java:34)
at org.rntgroup.CalcUnitTests.DivLongTest.lambda$unitDivByZeroLongTest$0(DivLongTest.java:31)
at org.testng.Assert.expectThrows(Assert.java:2444)
... 21 more
]]>
    </failure>
  </testcase> <!-- unitDivByZeroLongTest -->
</testsuite> <!-- org.rntgroup.CalcUnitTests.DivLongTest -->
